sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master


addons:
  ssh_known_hosts: ${IP}
before_install:
  - openssl aes-256-cbc -K $encrypted_024e66b057a6_key -iv $encrypted_024e66b057a6_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

script:
  - hexo generate
  - ls
  - tar -zcvf hexo.tar.bz2 ./public
  - scp -o stricthostkeychecking=no -r ./hexo.tar.bz2 root@${IP}:/www/wwwroot/blog.genji.xyz
  - ssh root@${IP} 'cd /www/wwwroot/blog.genji.xyz && tar -zxvf hexo.tar.bz2 '
  # - cd public
  # - echo 'blog.genji.xyz' > CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: public
