name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout@v2
      uses: actions/checkout@v2
    - run: ls
 

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x
        
    
    - name: install yarn
      run: | 
       yarn --version
       yarn install
       yarn build
       ls
           
