name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout@v2
      uses: actions/checkout@v2
    - run: ls
 

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x
        
    
    - name: install yarn
      run: | 
       npm --version
       npm install
       npm run build
       ls

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
